var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/modulos/backend/aula-73/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~~n95v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0nto3zx.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l_fbf6._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sftwx7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_modulos_backend_aula-73_page_actions_12101k8.js")
R.m(33431)
module.exports=R.m(33431).exports
