var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/modulos/infra/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__051ytno._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13rjphu.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_0bmr_52._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l_fbf6._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sftwx7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_modulos_infra_page_actions_0p75e81.js")
R.m(79063)
module.exports=R.m(79063).exports
