var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/modulos/backend/parte2/cursos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__025lvu1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-odcw6.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l_fbf6._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sftwx7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_modulos_backend_parte2_cursos_page_actions_0a8k6x5.js")
R.m(90733)
module.exports=R.m(90733).exports
