// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/alunos" | "/admin/dashboard" | "/admin/gabarito" | "/admin/login" | "/admin/trabalho1" | "/admin/turmas" | "/login" | "/modulos/backend" | "/modulos/backend/atividade-1" | "/modulos/backend/atividade-2" | "/modulos/backend/aula-71" | "/modulos/backend/aula-72" | "/modulos/backend/aula-73" | "/modulos/backend/hello-firebase" | "/modulos/backend/parte1" | "/modulos/backend/parte1/alunos" | "/modulos/backend/parte1/cursos" | "/modulos/backend/parte1/matriculas" | "/modulos/backend/parte1/turmas" | "/modulos/backend/parte2" | "/modulos/backend/parte2/alunos" | "/modulos/backend/parte2/cursos" | "/modulos/backend/parte2/matriculas" | "/modulos/backend/parte2/turmas" | "/modulos/dados" | "/modulos/dados/auth" | "/modulos/dados/deploy" | "/modulos/dados/desafio" | "/modulos/dados/firestore-escrita" | "/modulos/dados/firestore-leitura" | "/modulos/dados/projeto-base" | "/modulos/dados/server-actions" | "/modulos/infra" | "/modulos/infra/git" | "/modulos/infra/node-1" | "/modulos/infra/node-2" | "/modulos/infra/node-3" | "/modulos/infra/terminal" | "/modulos/infra/typescript" | "/modulos/nextjs" | "/modulos/nextjs/aula-02" | "/modulos/nextjs/aula-03" | "/modulos/nextjs/aula-04" | "/modulos/nextjs/aula-componentes" | "/modulos/nextjs/aula-paginas" | "/modulos/nextjs/data-fetching" | "/modulos/nextjs/data-fetching-api" | "/modulos/nextjs/desafio" | "/modulos/nextjs/intro" | "/modulos/nextjs/otimizacoes" | "/modulos/nextjs/tradedesk-lab" | "/modulos/nextjs/tradedesk-lab/submissao" | "/modulos/nextjs/tradedesk-lab/submissao/confirmado" | "/modulos/ui" | "/modulos/ui/componentes" | "/modulos/ui/dashboards" | "/modulos/ui/desafio" | "/modulos/ui/microinteracoes" | "/modulos/ui/shadcn" | "/modulos/ui/tailwind" | "/perfil/[id]" | "/progresso"
type AppRouteHandlerRoutes = "/api/admin/alunos/[uid]" | "/api/admin/aulas" | "/api/admin/login" | "/api/admin/logout" | "/api/admin/modules" | "/api/admin/trabalho1" | "/api/status-mercado" | "/api/trabalho1" | "/api/trabalho1/config"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/alunos": {}
  "/admin/dashboard": {}
  "/admin/gabarito": {}
  "/admin/login": {}
  "/admin/trabalho1": {}
  "/admin/turmas": {}
  "/api/admin/alunos/[uid]": { "uid": string; }
  "/api/admin/aulas": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/modules": {}
  "/api/admin/trabalho1": {}
  "/api/status-mercado": {}
  "/api/trabalho1": {}
  "/api/trabalho1/config": {}
  "/login": {}
  "/modulos/backend": {}
  "/modulos/backend/atividade-1": {}
  "/modulos/backend/atividade-2": {}
  "/modulos/backend/aula-71": {}
  "/modulos/backend/aula-72": {}
  "/modulos/backend/aula-73": {}
  "/modulos/backend/hello-firebase": {}
  "/modulos/backend/parte1": {}
  "/modulos/backend/parte1/alunos": {}
  "/modulos/backend/parte1/cursos": {}
  "/modulos/backend/parte1/matriculas": {}
  "/modulos/backend/parte1/turmas": {}
  "/modulos/backend/parte2": {}
  "/modulos/backend/parte2/alunos": {}
  "/modulos/backend/parte2/cursos": {}
  "/modulos/backend/parte2/matriculas": {}
  "/modulos/backend/parte2/turmas": {}
  "/modulos/dados": {}
  "/modulos/dados/auth": {}
  "/modulos/dados/deploy": {}
  "/modulos/dados/desafio": {}
  "/modulos/dados/firestore-escrita": {}
  "/modulos/dados/firestore-leitura": {}
  "/modulos/dados/projeto-base": {}
  "/modulos/dados/server-actions": {}
  "/modulos/infra": {}
  "/modulos/infra/git": {}
  "/modulos/infra/node-1": {}
  "/modulos/infra/node-2": {}
  "/modulos/infra/node-3": {}
  "/modulos/infra/terminal": {}
  "/modulos/infra/typescript": {}
  "/modulos/nextjs": {}
  "/modulos/nextjs/aula-02": {}
  "/modulos/nextjs/aula-03": {}
  "/modulos/nextjs/aula-04": {}
  "/modulos/nextjs/aula-componentes": {}
  "/modulos/nextjs/aula-paginas": {}
  "/modulos/nextjs/data-fetching": {}
  "/modulos/nextjs/data-fetching-api": {}
  "/modulos/nextjs/desafio": {}
  "/modulos/nextjs/intro": {}
  "/modulos/nextjs/otimizacoes": {}
  "/modulos/nextjs/tradedesk-lab": {}
  "/modulos/nextjs/tradedesk-lab/submissao": {}
  "/modulos/nextjs/tradedesk-lab/submissao/confirmado": {}
  "/modulos/ui": {}
  "/modulos/ui/componentes": {}
  "/modulos/ui/dashboards": {}
  "/modulos/ui/desafio": {}
  "/modulos/ui/microinteracoes": {}
  "/modulos/ui/shadcn": {}
  "/modulos/ui/tailwind": {}
  "/perfil/[id]": { "id": string; }
  "/progresso": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
