// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/alunos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/alunos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/alunos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/gabarito/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gabarito">> = Specific
  const handler = {} as typeof import("../../src/app/admin/gabarito/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/trabalho1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trabalho1">> = Specific
  const handler = {} as typeof import("../../src/app/admin/trabalho1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/turmas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/turmas">> = Specific
  const handler = {} as typeof import("../../src/app/admin/turmas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/atividade-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/atividade-1">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/atividade-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/atividade-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/atividade-2">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/atividade-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/aula-71/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/aula-71">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/aula-71/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/aula-72/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/aula-72">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/aula-72/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/aula-73/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/aula-73">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/aula-73/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/hello-firebase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/hello-firebase">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/hello-firebase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte1/alunos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte1/alunos">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte1/alunos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte1/cursos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte1/cursos">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte1/cursos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte1/matriculas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte1/matriculas">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte1/matriculas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte1">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte1/turmas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte1/turmas">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte1/turmas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte2/alunos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte2/alunos">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte2/alunos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte2/cursos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte2/cursos">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte2/cursos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte2/matriculas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte2/matriculas">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte2/matriculas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte2">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/backend/parte2/turmas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/backend/parte2/turmas">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/backend/parte2/turmas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/auth">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/deploy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/deploy">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/deploy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/desafio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/desafio">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/desafio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/firestore-escrita/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/firestore-escrita">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/firestore-escrita/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/firestore-leitura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/firestore-leitura">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/firestore-leitura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/projeto-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/projeto-base">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/projeto-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/dados/server-actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/dados/server-actions">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/dados/server-actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/git/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/git">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/git/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/node-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/node-1">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/node-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/node-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/node-2">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/node-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/node-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/node-3">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/node-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/terminal">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/infra/typescript/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/infra/typescript">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/infra/typescript/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/aula-02/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/aula-02">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/aula-02/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/aula-03/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/aula-03">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/aula-03/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/aula-04/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/aula-04">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/aula-04/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/aula-componentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/aula-componentes">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/aula-componentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/aula-paginas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/aula-paginas">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/aula-paginas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/data-fetching-api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/data-fetching-api">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/data-fetching-api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/data-fetching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/data-fetching">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/data-fetching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/desafio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/desafio">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/desafio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/intro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/intro">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/intro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/otimizacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/otimizacoes">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/otimizacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/tradedesk-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/tradedesk-lab">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/tradedesk-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/tradedesk-lab/submissao/confirmado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/tradedesk-lab/submissao/confirmado">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/tradedesk-lab/submissao/confirmado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/nextjs/tradedesk-lab/submissao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/nextjs/tradedesk-lab/submissao">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/nextjs/tradedesk-lab/submissao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/componentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/componentes">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/componentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/dashboards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/dashboards">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/dashboards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/desafio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/desafio">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/desafio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/microinteracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/microinteracoes">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/microinteracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/shadcn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/shadcn">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/shadcn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/modulos/ui/tailwind/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modulos/ui/tailwind">> = Specific
  const handler = {} as typeof import("../../src/app/modulos/ui/tailwind/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/perfil/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/perfil/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/progresso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/progresso">> = Specific
  const handler = {} as typeof import("../../src/app/progresso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/alunos/[uid]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/alunos/[uid]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/alunos/[uid]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/aulas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/aulas">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/aulas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/modules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/modules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/trabalho1/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trabalho1">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/trabalho1/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/status-mercado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status-mercado">> = Specific
  const handler = {} as typeof import("../../src/app/api/status-mercado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trabalho1/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trabalho1/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/trabalho1/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trabalho1/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trabalho1">> = Specific
  const handler = {} as typeof import("../../src/app/api/trabalho1/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
