var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/turmas/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12c4blg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0emuvrh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l_fbf6._.js")
R.c("server/chunks/ssr/node_modules_0jpep_m._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sftwx7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_turmas_page_actions_0chuczh.js")
R.m(77392)
module.exports=R.m(77392).exports
